# Generated by Django 3.2.9 on 2022-04-12 07:33

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user_icon_url', models.CharField(blank=True, max_length=200, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_date_of_birth', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_content', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_content', models.CharField(blank=True, max_length=200, null=True)),
                ('rating_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_content', models.CharField(blank=True, max_length=500, null=True)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('star_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'star',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalkPoint',
            fields=[
                ('walk_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('walk_point_x', models.FloatField(blank=True, null=True)),
                ('walk_point_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'walk_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VetHospital',
            fields=[
                ('vet_hospital_id', models.IntegerField(blank=True, null=True)),
                ('vet', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.user')),
            ],
            options={
                'db_table': 'vet_hospital',
                'managed': False,
            },
        ),
    ]
