# Generated by Django 3.2.9 on 2022-04-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_display_name',
            new_name='pet_name',
        ),
    ]
