# Generated by Django 3.2.9 on 2022-04-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifyRecord',
            new_name='EmailVerificationCode',
        ),
        migrations.AlterModelTable(
            name='emailverificationcode',
            table='email_verification_code',
        ),
    ]
