# Generated by Django 3.2.9 on 2022-04-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220421_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
