# Generated by Django 3.2.9 on 2022-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pet_pet_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_cover',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
