# Generated by Django 3.2.9 on 2022-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_post_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_vaccination_status',
            field=models.BooleanField(default=False),
        ),
    ]
