# Generated by Django 3.2.9 on 2022-05-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
