# Generated by Django 3.2.9 on 2022-05-22 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_comment_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracePath',
            fields=[
                ('trace_path_id', models.AutoField(primary_key=True, serialize=False)),
                ('trace_path_coordinates_url', models.CharField(blank=True, max_length=200, null=True)),
                ('trace_path_start_time', models.DateTimeField(blank=True, null=True)),
                ('trace_path_end_time', models.DateTimeField(blank=True, null=True)),
                ('trace_path_note', models.CharField(blank=True, max_length=200, null=True)),
                ('trace_path_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trace_path',
            },
        ),
    ]
