# Generated by Django 3.2.9 on 2022-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20220522_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
