# Generated by Django 3.2.9 on 2022-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_user_email_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_icon_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
