# Generated by Django 3.2.9 on 2022-06-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20220602_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
